### ISSUE TITLE
Migration support?

### ISSUE THREAD

**Issue by cinqi** [alan-cooney/knex-data-api-client#7]
Apparently this does not support knex migrations?

As PSQL is also GA for Data API, readme should also note that this works for MySQL only :)

**Comment by alan-cooney** [comment]
Hi @cinqi  - these features have both been added in this pull request - https://github.com/alan-cooney/knex-data-api-client/pull/6 . I'll be reviewing them and merging in shortly.

**Comment by DanielOrtel** [comment]
Bump. Any word on this?

**Comment by DanielOrtel** [comment]
So looking through the PRs, turns out [this fork](https://github.com/markusahlstrand/knex-data-api-client) added support for psql and migrations. Though it would be nice to have it as a dedicated package and not have to pull in a git repo. 

Edit: nvm, there's an [npm package](https://www.npmjs.com/package/knex-aurora-data-api-client) as well

**Comment by alan-cooney** [comment]
Hi @DanielOrtel that's right - it's been created as a separate package.
